### ISSUE TITLE
Inconsistencies with setTranslationFailedTAC("");

### ISSUE THREAD

**Issue by cb-steven-matison** [moryakovdv/iwxxmConverter#10]
Please uncomment line 662 in: SIGMETConverterV3.java
Please add similar code to line 500 in:  SPACEWEATHERConverterV3.java

My external testing solution is based on this value existing in the output xml.

**Comment by moryakovdv** [comment]
Thank you for pointing it out. 
I suspect, the correctly parsed message should not include this attribute at all. 
So, we should set it in output xml  only if the translation was failed.
I've commented code with setting empty attributes.
Is it possible for your solution to check existence of the attribute?

**Comment by cb-steven-matison** [comment]
Yes,  my logic is just making sure its empty.   I can adjust it either way I just need it consistent across all message types.   Since these 2 were only ones that didn't have it, adding it was easy on my end to resolve those 2 test types...

**Comment by cb-steven-matison** [comment]
We need to discuss the validation I have some ideas and some feedback about returning some json that indicates what caused the translation to fail all the way to maybe even translating what is there, and not breaking parse/convert completely on these test cases.

**Comment by moryakovdv** [comment]
So, closed. If changes in caeae8a is not sufficient for you, feel free to reopen.
Your ideas are indeed welcome.
