### ISSUE TITLE
REGEX Pattern Adjustment for "NSC" + New Line

### ISSUE THREAD

**Issue by cb-steven-matison** [moryakovdv/iwxxmConverter#11]
After retesting everything from latest commits,  I have a few tests that need attention.  These correspond to messages that have issues with NSC + a new trailing line on end of file.

This first example speci-A3-2.tac from the test data set repo ([https://github.com/cb-steven-matison/iwxxm-sample-data](https://github.com/cb-steven-matison/iwxxm-sample-data)) 

Works:
```
SPECI YUDO 151115Z 05025G37KT 3000 1200NE+TSRA BKN005CB 25/22 Q1008 TEMPO TL1200 0600
BECMG AT1200 8000 NSW NSC
```

Null Pointer:
```
SPECI YUDO 151115Z 05025G37KT 3000 1200NE+TSRA BKN005CB 25/22 Q1008 TEMPO TL1200 0600
BECMG AT1200 8000 NSW NSC

```
There are 3 more examples:

taf-OIZC-131130Z.tac (still fails with or without newline)
taf-SARP-131100Z.tac
taf-SARP-131251Z.tac

Also note, that when these messages fail, they are still throwing a null pointer exception as follows:
```
java.lang.NullPointerException
	at org.gamc.spmi.iwxxmConverter.wmo.WMORegister.getWMOUrlByCode(WMORegister.java:172)
```

**Comment by cb-steven-matison** [comment]
Another sample is metar-USTR-290030Z.tac

**Comment by moryakovdv** [comment]
Please check the #0f0f6de and let me know about results.
I'm on holidays till mid-august, so no further updates till that date.

**Comment by cb-steven-matison** [comment]
speci-A3-2.tac seems to work now.  The TAC/METAR examples still fail.


In regards to getWMOUrlByCode it appears these test are now reporting the following error:

```
nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException
	at org.gamc.spmi.iwxxmConverter.marshallers.v3.METARConverterV3.createCloudSectionTag(METARConverterV3.java:696)
	at org.gamc.spmi.iwxxmConverter.marshallers.v3.METARConverterV3.createMETARRecordTag(METARConverterV3.java:549)
	at org.gamc.spmi.iwxxmConverter.marshallers.v3.METARConverterV3.convertMessage(METARConverterV3.java:220)
	at org.gamc.spmi.iwxxmConverter.marshallers.v3.METARConverterV3.convertTacToXML(METARConverterV3.java:140)
	at org.gamc.spmi.iwxxmconverterrest.controllers.ConverterControllerV3.convertUndefinedMessage(ConverterControllerV3.java:89)
```

**Comment by cb-steven-matison** [comment]
This comment is for debugging metar-EDDF-runwaystate.tac:

`METAR EDDF 120550Z 03015KT 1400 R07R/P2000N R07C/P2000N R07L/1900U SN DRSN BR VV/// M04/M04 Q1000 R07R/11//90 R07C/15//90 R07L/15//90 BECMG 4000 NSW`

When the above message was first tested it was throwing a null pointer when creating an invalid object for vertical visibility "VV///".  I tested a working sample of code as "VV000" and "VV015".    I then validated in source code that the cloudS.getHeight is expecting an INTEGER and does not except the null scenario for "VV///".  I tested concept with feeding 0 to confirm.   Next I created a class for the nilReason in file (IWXXM31Helpers.java) by copying the original class, commenting some lines and adding the nilReason passed into the class call.  In this test scenario the nilReason should be "notObservable".   That Nil Reason class looks like:

```
        /**Creates tag for nilReason vertical visibility*/
	public  JAXBElement<LengthWithNilReasonType> createVerticalVisibilitySectionWithNilReason(String nilReasonUrl) {
		LengthWithNilReasonType vvType = ofIWXXM.createLengthWithNilReasonType();
		vvType.getNilReason().add(nilReasonUrl); 
                return ofIWXXM.createAerodromeCloudForecastTypeVerticalVisibility(vvType);
	}
```

Modification in file (METARConverterV3.java) looks like:

```
                       logger.debug("Attempting debug of cloudS verticle Visibility of VV///");
                        if (cloudS.getAmount().equalsIgnoreCase(WMOCloudRegister.verticalVisibilityCode)) {
				String nilReasonUrl = iwxxmHelpers.getNilRegister().getWMOUrlByCode("notObservable");
				JAXBElement<LengthWithNilReasonType> vVisibility = iwxxmHelpers
						.createVerticalVisibilitySectionWithNilReason(nilReasonUrl);
				cloud.setVerticalVisibility(vVisibility);

```

After completing the next test below, I adjusted above for nilReasonUrl (was just nilReason previously) and retested to confirm worked.

**Comment by cb-steven-matison** [comment]
This comment is for debugging metar-USTR-290030Z.tac 

`SPECI USTR 290030Z 35001MPS 1100 0900N R21/1900 +SHSN VV003 M02/M03 Q0996 R21/590742 TEMPO 0500 +SHSN VV002
`
Null pointer is:

```
java.lang.NullPointerException
	at org.gamc.spmi.iwxxmConverter.wmo.WMORegister.getWMOUrlByCode(WMORegister.java:174)
	at org.gamc.spmi.iwxxmConverter.marshallers.v3.IWXXM31Helpers.createCloudLayerSection(IWXXM31Helpers.java:446)
	at org.gamc.spmi.iwxxmConverter.marshallers.v3.METARConverterV3.createCloudSectionTag(METARConverterV3.java:734)
	at org.gamc.spmi.iwxxmConverter.marshallers.v3.METARConverterV3.createTrendResultsSection(METARConverterV3.java:443)
```

An adjustment made in file: METARConverterV3.java

Lines 732 - 737

```
		if (cloudS.getAmount()!=null && cloudS.getAmount().equalsIgnoreCase(WMOCloudRegister.verticalVisibilityCode)) {
				String nilReasonUrl = iwxxmHelpers.getNilRegister().getWMOUrlByCode("missing");
				//cloudLayer.setCloudLayer(iwxxmHelpers.createCloudLayerSection(cloudS.getAmount(), cloudS.getHeight(),
				//		cloudS.getType(), nilReasonUrl, LENGTH_UNITS.FT));
				cloudsType.getNilReason().add(nilReasonUrl);
			} 
```

Adjustment was to comment out the cloudLayer.setCloudLayer.  This is an empty cloud layer so creating the object with Height and Amount is passing invalid objects to createCloudLayerSection.  I believe we want to just create this section as nillable.

**Comment by cb-steven-matison** [comment]
In debugging taf-OIZC-131130Z.tac there are adjustments needed to create the cloud layer section when cloudSection.getAmount() is empty/nil.

```
TAF OIZC 131130Z 1312/1418 11004MPS 4000 HZ NSC
TEMPO 1312/1317 12008MPS FEW020TCU SCT025 BKN070
BECMG 1403/1405 7000 NSC
TEMPO 1408/1415 12009MPS 4000 SA NSC
```

The null pointer is:
```
java.lang.NullPointerException
	at org.gamc.spmi.iwxxmConverter.marshallers.v3.TAFConverterV3.createCloudSectionTag(TAFConverterV3.java:626)
	at org.gamc.spmi.iwxxmConverter.marshallers.v3.TAFConverterV3.createBaseResultSection(TAFConverterV3.java:367)
	at org.gamc.spmi.iwxxmConverter.marshallers.v3.TAFConverterV3.convertMessage(TAFConverterV3.java:193)
	at org.gamc.spmi.iwxxmConverter.marshallers.v3.TAFConverterV3.convertTacToXML(TAFConverterV3.java:120)

```

I made several attempts at similar code changes in TAFConverterV3.java and still cannot get around the null pointer for amount.setHref(cloudReg.getWMOUrlByCode(cloudAmount));

In these samples there either is no cloud amount or no VV.  This needs adjustment to the logic in the first conditional so that createEmptyCloudLayer works to create a fully nillable object when required artifacts are missing.   

Code change attempts and comments on results

```
			logger.debug("Attempting debug of TAF");

			if (cloudSection.getAmount().equalsIgnoreCase(WMOCloudRegister.verticalVisibilityCode)) {
				JAXBElement<LengthWithNilReasonType> vVisibility = iwxxmHelpers
						.createVerticalVisibilitySection(cloudSection.getHeight());
				clouds.setVerticalVisibility(vVisibility);

                                // i attempted similar to METAR and this did not work
				//String nilReasonUrl = iwxxmHelpers.getNilRegister().getWMOUrlByCode("missing");
				//JAXBElement<LengthWithNilReasonType> vVisibility = iwxxmHelpers
				//		.createVerticalVisibilitySectionWithNilReason(nilReasonUrl);
				//clouds.setVerticalVisibility(vVisibility);
                                
                                // i tested nil reason missing (like next conditionals) and that did not work
                                //String nilReasonUrl = iwxxmHelpers.getNilRegister().getWMOUrlByCode("missing");
				//cloudsType.getNilReason().add(nilReasonUrl);
                                
                                // i tested make this condition not trigger 
                                // added/removed cloudSection.getAmount() == null && 
                                // when i did this the bottom conditional else triggered and returned similar error with cloudAmount
			} 
```

**Comment by cb-steven-matison** [comment]
METAR and TAF samples that are still failing seem to be failing when cloudAmount = VV.  This is not a cloud Amount it is VerticalVisiblity.  This seems to be consistent across all debug samples.   I also started working on another metar issue with "1/8SM" and "3/4SM" and was able to get into the same situation where VV015 was caught as a cloud Amount of VV.  In all of these samples I am catching debug output:  Searching the VV in codes.wmo.int-49-2-CloudAmountReportedAtAerodrome.rdf 

Revert these changes since the only test case it resolved was actual test with VV///

**Comment by cb-steven-matison** [comment]
We need a common method across TAF/METAR samples to clearly create the empty cloud layer when VV is missing or VV/// (notObservable).   The helper function createEmptyCloudLayerSection needs to be called in these 2 scenarios (only instances are currently commented) instead of attempting createCloudLayerSection when required pieces are missing.

**Comment by moryakovdv** [comment]
Please, check #32f2eb1

**Comment by steven-matison** [comment]
Thats quite a commit.  I will try and test later today.   Great work!!

**Comment by steven-matison** [comment]
Was not able to complete build...looking for source of WMORegisterException.

!!!! import org.gamc.spmi.iwxxmConverter.wmo.WMORegister.WMORegisterException;

Not found in:
iwxxmConverter.CB/iwxxmCore/src/main/java/org/gamc/spmi/iwxxmConverter/wmo/WMORegister.java

**Comment by moryakovdv** [comment]
Probably I should place it into separate java file

**Comment by moryakovdv** [comment]
stale. Closing for now
